config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show]
  resources :trips, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :schedules, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :events, only: [:show, :new, :create, :edit, :update, :destroy]
    end

    resources :lists, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :items, only: [:new, :create, :edit, :update, :destroy]
      get 'items/:id', to: 'items#checked'
    end

  end

  root to: "users#show"
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :trip
  has_many :items

  validates :name, presence: true
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :trip_users, dependent: :destroy
  has_many :users, through: :trip_users
  has_many :schedules, dependent: :destroy
  has_many :events, through: :schedules, dependent: :destroy # scheduleを経由してeventをhas_mamy
  has_many :lists, dependent: :destroy
  has_many :items, through: :lists, dependent: :destroy # listを経由してitemをhas_mamy

  with_options presence: true do
    validates :name, :text, :destination, :start_day, :finish_day
  end

  validate :date_before_start
  validate :start_end_check

  def date_before_start # 開始日は今日以降の日付
    return if start_day.blank? # 空かどうかを判定

    errors.add(:start_day, 'は今日以降の日付を選択してください') if start_day < Date.today
  end

  def start_end_check # 日付の前後をチェック
    return if finish_day.blank? || start_day.blank? # 空かどうかを判定

    errors.add(:finish_day, 'の日付を正しく記入して下さい') unless start_day < finish_day
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_trip
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_action :move_to_root

  def show
    @items = @list.items.order('created_at ASC')
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to trip_path(@trip.id), notice: 'リストページを作成しました。'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to trip_list_path(@trip.id, @list.id), notice: 'リストページを更新しました。'
    else
      render :edit
    end
  end

  def destroy
    if @list.destroy
      redirect_to trip_path(@trip.id), notice: 'リストページを削除しました。'
    else
      flash.now[:alart] = '削除できないリストページです。'
      redirect_to trip_path(@trip.id)
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :text).merge(trip_id: params[:trip_id])
  end

  def set_trip
    @trip = Trip.includes(lists: :items).find(params[:trip_id]) # N+1問題対策
  end

  def set_list
    @list = List.includes(:items).find(params[:id]) # N+1問題対策
  end

  def move_to_root
    redirect_to root_path unless user_signed_in? && @trip.user_ids.include?(current_user.id)
  end
end

app/views/lists/edit.html.erb
<div class="backscreen">
  <div class="new-list-content">
    <div class="list-title">
      <h1>リストページ編集</h1>
    </div>

    <%= render "shared/list_form" %>

  </div>
</div>

app/views/lists/new.html.erb
<div class="backscreen">
  <div class="new-list-content">
    <div class="list-title">
      <h1>新規リストページ作成</h1>
    </div>

    <%= render "shared/list_form" %>

  </div>
</div>

app/views/lists/show.html.erb
<div class="backscreen">
  <div class="wrapper">
    <div class="side-bar">
      <div class="side-bar-upper">
        <h2><%= current_user.nickname %></h2>
      </div>
      <div class="side-bar-lower">
        <% if user_signed_in? && @trip.user_ids.include?(current_user.id) %> 
          <ul>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
            <li><%= link_to 'アカウント設定', "#" %></li>
            <li><%= link_to 'リスト項目作成', new_trip_list_item_path(@trip.id, @list.id) %></li>
            <li><%= link_to 'リスト編集', edit_trip_list_path(@trip.id, @list.id) %></li>
            <li><%= link_to 'リスト削除', trip_list_path(@trip.id, @list.id), method: :delete %></li>
            <li><%= link_to 'しおり詳細へ戻る', trip_path(@trip.id) %></li>
            <li><%= link_to 'しおり一覧へ戻る', root_path %></li>
          </ul>
        <% end %>
      </div>
    </div>

    <div class="main-container">
      <% breadcrumb :list, @list %>
      <%= breadcrumbs separator: " &rsaquo; " %>
      <div class="list-titile">
        <h1><%= @list.name %></h1>
        <h3><%= @trip.name %></h3>
      </div>
    
      <div class="list-details">
        <div class="trip-created-at">
          <p>作成日:<%= l @list.created_at, format: :day  %></p>
        </div>
        <div class="list-details-items">
          <% if @list.text.present? %>
            <div class="details-title">概要</div>
            <p><%= @list.text %></p>
          <% end %>
        </div>
      </div>

      <div class="items-container">
        <ul class="item-lists">
          <% @items.each do |item| %>
            <li class='item-list'>
              <div class="item-info">
                <div class="item-checked" data-id-1=<%= item.list.trip_id %> data-id-2=<%= item.list_id %> data-id-3=<%= item.id %> data-check=<%= item.checked %>>
                  <div class="item-info-left" id="check-box">
                    □
                  </div>
                
                  <div class="item-info-center">
                    <p class="item-info-name"><strong><%= item.name %></strong></p>
                    <p class="item-info-text"><%= item.text %></p>
                    <p class="item-info-text"><%= l item.created_at, format: :day %></p>
                  </div>
                </div>
                <div class="item-info-right">
                  <ul>
                    <li><%= link_to '編集', edit_trip_list_item_path(@trip.id, @list.id, item.id) %></li>
                    <li><%= link_to '削除', trip_list_item_path(@trip.id, @list.id, item.id), method: :delete %></li>
                  </ul>
                </div>
              </div>
            </li>
          <% end %>
        </ul> 

      </div>
    </div>

  </div>
</div>