config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show]
  resources :trips, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :schedules, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :events, only: [:show, :new, :create, :edit, :update, :destroy]
    end

    resources :lists, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :items, only: [:new, :create, :edit, :update, :destroy]
      get 'items/:id', to: 'items#checked'
    end

  end

  root to: "users#show"
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :trip_users, dependent: :destroy
  has_many :users, through: :trip_users
  has_many :schedules, dependent: :destroy
  has_many :events, through: :schedules, dependent: :destroy # scheduleを経由してeventをhas_mamy
  has_many :lists, dependent: :destroy
  has_many :items, through: :lists, dependent: :destroy # listを経由してitemをhas_mamy

  with_options presence: true do
    validates :name, :text, :destination, :start_day, :finish_day
  end

  validate :date_before_start
  validate :start_end_check

  def date_before_start # 開始日は今日以降の日付
    return if start_day.blank? # 空かどうかを判定

    errors.add(:start_day, 'は今日以降の日付を選択してください') if start_day < Date.today
  end

  def start_end_check # 日付の前後をチェック
    return if finish_day.blank? || start_day.blank? # 空かどうかを判定

    errors.add(:finish_day, 'の日付を正しく記入して下さい') unless start_day < finish_day
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]
  before_action :move_to_root, only: [:edit, :update, :destroy]

  def show
    @schedules = @trip.schedules.includes(:events).order('day ASC')
    @lists = @trip.lists.includes(:items).order('created_at DESC')
    @members = User.where(id: @trip.user_ids)

    @trip_cost = 0
    @schedules.each do |schedule|
      day_cost = 0 # イベント毎の金額を合計し、一日毎(スケジュール毎)の金額を取得
      schedule.events.each do |event|
        unless event.price.nil?
          cost = event.price
          day_cost += cost
        end
      end
      @trip_cost += day_cost # スケジュール毎の金額を合計し、旅行全体の金額に
    end
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    if @trip.save
      redirect_to root_path, notice: 'しおりを作成しました。'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @trip.update(trip_params)
      redirect_to trip_path(@trip.id), notice: 'しおりを更新しました。'
    else
      render :edit
    end
  end

  def destroy
    if @trip.destroy
      redirect_to root_path, notice: 'しおりを削除しました。'
    else
      flash.now[:alart] = '削除できないしおりです。'
      redirect_to root_path
    end
  end

  private

  def trip_params
    params.require(:trip).permit(:name, :text, :destination, :start_day, :finish_day, user_ids: [])
  end

  def set_trip
    @trip = Trip.includes(trip_users: :user, schedules: :events, lists: :items).find(params[:id]) # N+1問題対策
  end

  def move_to_root
    redirect_to root_path unless user_signed_in? && @trip.user_ids.include?(current_user.id)
  end
end

app/views/trips/edit.html.erb
<div class="backscreen">
  <div class="new-trip-content">
    <div class="page-title">
      <h1>しおり編集</h1>
    </div>
    
    <%= render "shared/trip_form" %>

  </div>
</div>

app/views/trips/new.html.erb
<div class="backscreen">
  <div class="new-trip-content">
    <div class="page-title">
      <h1>新規しおり作成</h1>
    </div>

    <%= render "shared/trip_form" %>

  </div>
</div>

app/views/trips/show.html.erb
<div class="backscreen">
  <div class="wrapper">
    <div class="side-bar">
      <div class="side-bar-upper">
        <h2><%= current_user.nickname %></h2>
      </div>
      <div class="side-bar-lower">
        <% if user_signed_in? && @trip.user_ids.include?(current_user.id) %> 
          <ul>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
            <li><%= link_to 'アカウント設定', "#" %></li>
            <li><%= link_to 'スケジュール作成', new_trip_schedule_path(@trip.id) %></li>
            <li><%= link_to 'リスト作成', new_trip_list_path(@trip.id) %></li>
            <li><%= link_to 'しおり編集', edit_trip_path(@trip.id) %></li>
            <li><%= link_to 'しおり削除', trip_path(@trip.id), method: :delete %></li>
            <li><%= link_to 'しおり一覧へ戻る', root_path %></li>
          </ul>
        <% end %>
      </div>
    </div>

    <div class="main-container">
      <% breadcrumb :trip, @trip %>
      <%= breadcrumbs separator: " &rsaquo; " %> 
      <div class="trip-title">
        <h1><%= @trip.name %></h1>
      </div>
      <div class="trip-details">
        <div class="trip-created-at">
          <p>作成日:<%= l @trip.created_at, format: :day  %></p>
        </div>
        <div class="trip-details-items">
          <div class="details-title">概要</div>
          <p><%= @trip.text %></p>
        </div>
        <div class="trip-details-items">
          <div class="details-title">目的地</div>
          <p><%= @trip.destination %></p>
        </div>
        <div class="trip-details-items">
          <div class="details-title">旅行期間</div>
          <p><%= @trip.start_day %> 〜 <%= @trip.finish_day %></p>
        </div>
        <div class="trip-details-items">
          <div class="details-title">参加メンバー</div>
          <p>
            <% @members.each do |member| %>
              <%= member.nickname %>
            <% end %>
          </p>
        </div>
        <% if @trip_cost != 0 %>
          <div class="trip-details-items">
            <div class="details-title">旅行の予算(円/人)</div>
            <p><%= number_with_delimiter @trip_cost %>円/人</p>
          </div>
        <% end %>
      </div>


      <div class="schedules-container">
        <ul class="schedule-lists">
          <% @schedules.each do |schedule| %>
            <li class='schedule-list'>
              <%= link_to trip_schedule_path(@trip.id, schedule.id) do %>
                <div class="schedule-info">
                  <p class="schedule-name"><strong><%= schedule.name %></strong></p>
                  <p class="icon-name">schedule</p>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul>   
      </div>


      <div class="lists-container">
        <ul class="list-lists">
          <% @lists.each do |list| %>
            <li class='list-list'>
              <%= link_to trip_list_path(@trip.id, list.id) do %>
                <div class="list-info">
                  <p class="list-name"><strong><%= list.name %></strong></p>
                  <p class="icon-name">list</p>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>



    </div>

  </div>
</div>