config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show]
  resources :trips, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :schedules, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :events, only: [:show, :new, :create, :edit, :update, :destroy]
    end

    resources :lists, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :items, only: [:new, :create, :edit, :update, :destroy]
      get 'items/:id', to: 'items#checked'
    end

  end

  root to: "users#show"
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :trip
  has_many :events, dependent: :destroy

  with_options presence: true do
    validates :name, :text, :day
  end

  validate :date_before_start

  def date_before_start # 日付は今日以降
    return if day.blank? # 空かどうかを判定

    errors.add(:day, 'は今日以降の日付を選択してください') if day < Date.today
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :trip_users, dependent: :destroy
  has_many :users, through: :trip_users
  has_many :schedules, dependent: :destroy
  has_many :events, through: :schedules, dependent: :destroy # scheduleを経由してeventをhas_mamy
  has_many :lists, dependent: :destroy
  has_many :items, through: :lists, dependent: :destroy # listを経由してitemをhas_mamy

  with_options presence: true do
    validates :name, :text, :destination, :start_day, :finish_day
  end

  validate :date_before_start
  validate :start_end_check

  def date_before_start # 開始日は今日以降の日付
    return if start_day.blank? # 空かどうかを判定

    errors.add(:start_day, 'は今日以降の日付を選択してください') if start_day < Date.today
  end

  def start_end_check # 日付の前後をチェック
    return if finish_day.blank? || start_day.blank? # 空かどうかを判定

    errors.add(:finish_day, 'の日付を正しく記入して下さい') unless start_day < finish_day
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_trip
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]
  before_action :move_to_root

  def show
    @events = @schedule.events.with_attached_images.order('start_time ASC') # N+1問題対策(images)

    @day_cost = 0 # イベント毎の金額をけ合計し、一日毎(スケジュールページ)の金額を表示
    @events.each do |event|
      unless event.price.nil?
        cost = event.price
        @day_cost += cost
      end
    end
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      redirect_to trip_path(@trip.id), notice: 'スケジュールページを作成しました。'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @schedule.update(schedule_params)
      redirect_to trip_schedule_path(@trip.id, @schedule.id), notice: 'スケジュールページを更新しました。'
    else
      render :edit
    end
  end

  def destroy
    if @schedule.destroy
      redirect_to trip_path(@trip.id), notice: 'スケジュールページを削除しました。'
    else
      flash.now[:alart] = '削除できないスケジュールページです。'
      redirect_to trip_path(@trip.id)
    end
  end

  private

  def schedule_params
    params.require(:schedule).permit(:name, :text, :day).merge(trip_id: params[:trip_id])
  end

  def set_trip
    @trip = Trip.includes(trip_users: :user, schedules: :events).find(params[:trip_id]) # N+1問題対策
  end

  def set_schedule
    @schedule = Schedule.includes(:events).find(params[:id]) # N+1問題対策
  end

  def move_to_root
    redirect_to root_path unless user_signed_in? && @trip.user_ids.include?(current_user.id)
  end
end

app/views/schedules/edit.html.erb
<div class="backscreen">
  <div class="new-schedule-content">
    <div class="schedule-title">
      <h1>スケジュールページ編集</h1>
    </div>

    <%= render "shared/schedule_form" %>

  </div>
</div>

app/views/schedules/new.html.erb
<div class="backscreen">
  <div class="new-schedule-content">
    <div class="schedule-title">
      <h1>新規スケジュールページ作成</h1>
    </div>

    <%= render "shared/schedule_form" %>
    
  </div>
</div>

app/views/schedules/show.html.erb
<div class="backscreen">
  <div class="wrapper">
    <div class="side-bar">
      <div class="side-bar-upper">
        <h2><%= current_user.nickname %></h2>
      </div>
      <div class="side-bar-lower">
        <% if user_signed_in? && @trip.user_ids.include?(current_user.id) %> 
          <ul>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
            <li><%= link_to 'アカウント設定', "#" %></li>
            <li><%= link_to 'イベント作成', new_trip_schedule_event_path(@trip.id, @schedule.id) %></li>
            <li><%= link_to 'スケジュール編集', edit_trip_schedule_path(@trip.id) %></li>
            <li><%= link_to 'スケジュール削除', trip_schedule_path(@trip.id, @schedule.id), method: :delete %></li>
            <li><%= link_to 'しおり詳細へ戻る', trip_path(@trip.id) %></li>
            <li><%= link_to 'しおり一覧へ戻る', root_path %></li>
          </ul>
        <% end %>
      </div>
    </div>

    <div class="main-container">
      <% breadcrumb :schedule, @schedule %>
      <%= breadcrumbs separator: " &rsaquo; " %>
      <div class="schedule-titile">
        <h1><%= @schedule.name %></h1>
        <h3><%= @trip.name %></h3>
      </div>
      
      <div class="schedule-details">
        <div class="trip-created-at">
          <p>作成日:<%= l @schedule.created_at, format: :day  %></p>
        </div>

        <div class="schedule-details-items">
          <div class="details-title">日付</div>
          <p><%= @schedule.day %></p>
        </div>

        <div class="schedule-details-items">
          <div class="details-title">概要</div>
          <p><%= @schedule.text %></p>
        </div>
        
        <% if @day_cost != 0 %>
          <div class="schedule-details-items">
            <div class="details-title">この日の金額</div>
            <p><%= number_with_delimiter @day_cost %>円/人</p>
          </div>
        <% end %>
      </div>

      

      <div class="events-container">
        <ul class="event-lists">
          <% @events.each do |event| %>
            <li class='event-list'>
              <%= link_to trip_schedule_event_path(@trip.id, @schedule.id, event.id) do %>
                <div class="event-info">
                  <div class="event-info-left">
                    <p><%= event.day %></p>
                    <p><strong><%= l event.start_time, format: :short %></strong></p>
                    <p><strong>↓</strong></p>
                    <p><strong><%= l event.finish_time, format: :short %></strong></p>
                  </div>
                  <div class="event-info-right">
                    <div class="event-info-right-upper">
                      <p class="event-info-name"><strong><%= event.name %></strong></p>
                      <p class="event-info-price">
                        <% if event.price != nil %>
                          <%= number_with_delimiter event.price %>円/人
                        <% end %>
                      </p>
                    </div>
                    <div class="event-info-right-lower">
                      <div>
                        <p class="event-info-place"><%= event.place %></p>
                        <p class="event-info-text"><%= event.text %></p>
                      </div>
                      <div class="event-image-icon">
                        <% if event.images.attached? %>
                          <i class="fas fa-camera fa-2x"></i>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul> 
      </div>
    </div>

  </div>
</div>