config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show]
  resources :trips, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :schedules, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :events, only: [:show, :new, :create, :edit, :update, :destroy]
    end

    resources :lists, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :items, only: [:new, :create, :edit, :update, :destroy]
      get 'items/:id', to: 'items#checked'
    end

  end

  root to: "users#show"
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :trip_users, dependent: :destroy
  has_many :users, through: :trip_users
  has_many :schedules, dependent: :destroy
  has_many :events, through: :schedules, dependent: :destroy # scheduleを経由してeventをhas_mamy
  has_many :lists, dependent: :destroy
  has_many :items, through: :lists, dependent: :destroy # listを経由してitemをhas_mamy

  with_options presence: true do
    validates :name, :text, :destination, :start_day, :finish_day
  end

  validate :date_before_start
  validate :start_end_check

  def date_before_start # 開始日は今日以降の日付
    return if start_day.blank? # 空かどうかを判定

    errors.add(:start_day, 'は今日以降の日付を選択してください') if start_day < Date.today
  end

  def start_end_check # 日付の前後をチェック
    return if finish_day.blank? || start_day.blank? # 空かどうかを判定

    errors.add(:finish_day, 'の日付を正しく記入して下さい') unless start_day < finish_day
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_event_form.html.erb
<div class="schedule-day">
  <h5>スケジュール日：<%= @schedule.day %></h5>
</div>

<div class="event-main">
  <%= form_with model: [@trip, @schedule, @event], local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="form-title">
      イベント名
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :name, class:"event-text", id:"event-name", placeholder:"例：新幹線移動" %>

    <div class="form-title">
      イベント概要
    </div>
    <%= f.text_area :text, class:"event-text", id:"event-info", placeholder:"例：はやぶさ〇〇号" %>

    <div class="date-input">
      <div class="event-date-input">
        <div class="form-title">
          日付
          <span class="indispensable">必須</span>
        </div>
        <div class='input-date-wrap'> 
          <%= raw sprintf(
                  f.date_select(
                    :day,
                    class:'select-date',
                    id:"start-date",
                    use_month_numbers: true,
                    start_year: Time.now.year,
                    end_year: (Time.now.year + 5),
                    selected: @schedule.day, 
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
        </div>
      </div>
    </div>

    <div class="date-input">
      <div class="start-date-input">
        <div class="form-title">
          開始時間
          <span class="indispensable">必須</span>
        </div>
        <div class='input-date-wrap'>
          <%= f.time_select(:start_time, {class:'select-date', id:"start-time", prompt:'--', time_separator: ':'}, ignore_data: true) %>
        </div>
      </div>

      <div class="finish-date-input"> 
        <div class="form-title">
          終了時間
          <span class="indispensable">必須</span>
        </div>
        <div class='input-date-wrap'>
          <%= f.time_select(:finish_time, {class:'select-date', id:"finish-time", prompt:'--', ignore_data: true, time_separator: ':'}) %>
        </div>
      </div>
    </div>

    <div class="form-title">
      場所
    </div>
    <%= f.text_area :place, class:"event-text", id:"event-place", placeholder:"例：東京駅新幹線ホーム" %>

    <div class="form-title">
      URL
    </div>
    <%= f.text_area :url, class:"event-text", id:"event-url", placeholder:"例：https://....." %>

    <div class="form-title">
      金額(円/人) ※一人あたり
    </div>
    <%= f.text_field :price, class:"event-text", id:"event-price", placeholder:"例：15000" %>

    <div class="form-title">
      写真 ※複数選択可(CtrlやShiftキーを押しながら選択してください)
    </div>
    <div class="input-area">
      <%= f.file_field :images, class: 'event[images][]', id:"event-image",  multiple: true %>
      <div id="image-preview">
        <div>
          <% @event.images.each do |image| %>
            <%= image_tag image, id: 'event-img' %>
          <% end %>
        </div>
      </div> 
    </div>

    <%# 作成・編集ボタン %>
    <% if @event.id != nil %>
      <div class="create-btn-contents">
        <%= f.submit "編集する" ,class:"create-btn" %>
        <%=link_to 'もどる', trip_schedule_event_path(@trip.id, @schedule.id, @event.id), class:"back-btn" %>
      </div>
    <% else %>
      <div class="create-btn-contents">
        <%= f.submit "作成する" ,class:"create-btn" %>
        <%=link_to 'もどる', trip_schedule_path(@trip.id, @schedule.id), class:"back-btn" %>
      </div>
    <% end %>
        
  <% end %>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alart] %>
  <div class="alert alert-danger">
    <%= flash[:alart] %>
  </div>
<% end %>

app/views/shared/_item_form.html.erb
<div class="trip-days">
  <h5>旅行日程：<%= @trip.start_day %> 〜 <%= @trip.finish_day %></h5>
</div>

<div class="item-main">
  <%= form_with model: [@trip, @list, @item], local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="form-title">
      項目名
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :name, class:"item-text", id:"item-name", placeholder:"例：職場へのお土産" %>

    <div class="form-title">
      概要
    </div>
    <%= f.text_area :text, class:"item-text", id:"item-info", placeholder:"例：20個入りくらいの箱菓子" %>

    <%# 作成・編集ボタン %>
    <% if @list.id != nil %>
      <div class="create-btn-contents">
        <%= f.submit "編集する" ,class:"create-btn" %>
        <%=link_to 'もどる', trip_list_path(@trip.id, @list.id), class:"back-btn" %>
      </div>
    <% else %>
      <div class="create-btn-contents">
        <%= f.submit "作成する" ,class:"create-btn" %>
        <%=link_to 'もどる', trip_list_path(@trip.id, @list.id), class:"back-btn" %>
      </div>
    <% end %>
        
  <% end %>
</div>

app/views/shared/_list_form.html.erb
<div class="trip-days">
  <h5>旅行日程：<%= @trip.start_day %> 〜 <%= @trip.finish_day %></h5>
</div>

<div class="list-main">
  <%= form_with model: [@trip, @list], local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="form-title">
      リスト名
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :name, class:"list-text", id:"list-name", placeholder:"例：買い物リスト" %>

    <div class="form-title">
      リスト概要
    </div>
    <%= f.text_area :text, class:"list-text", id:"list-info", placeholder:"例：自分が欲しいものと、お土産買っていく人をリスト化" %>

    <%# 作成・編集ボタン %>
    <% if @list.id != nil %>
      <div class="create-btn-contents">
        <%= f.submit "編集する" ,class:"create-btn" %>
        <%=link_to 'もどる', trip_list_path(@trip.id, @list.id), class:"back-btn" %>
      </div>
    <% else %>
      <div class="create-btn-contents">
        <%= f.submit "作成する" ,class:"create-btn" %>
        <%=link_to 'もどる', trip_path(@trip.id), class:"back-btn" %>
      </div>
    <% end %>
        
  <% end %>
</div>

app/views/shared/_schedule_form.html.erb
<div class="trip-days">
  <h5>旅行日程：<%= @trip.start_day %> 〜 <%= @trip.finish_day %></h5>
</div>

<div class="schedule-main">
  <%# @tripと@scheduleのそれぞれの中身でcreateとupdateを自動で判定 %>
  <%= form_with(model: [@trip, @schedule], local: true) do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="form-title">
      スケジュールページ名
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :name, class:"schedule-text", id:"schedule-name", placeholder:"例：◯月◯日 1日目" %>

    <div class="form-title">
      スケジュールページ概要
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :text, class:"schedule-text", id:"schedule-info", placeholder:"例：移動とホテル近場の観光がメインの日" %>

    <div class="date-input">
      <div class="start-date-input">
        <div class="form-title">
          日付
          <span class="indispensable">必須</span>
        </div>
        <div class='input-date-wrap'>
          <%= raw sprintf(
                  f.date_select(
                    :day,
                    class:'select-date',
                    id:"start-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: Time.now.year,
                    end_year: (Time.now.year + 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
        </div>
      </div>
    </div>

    <%# 作成・編集ボタン %>
    <% if @schedule.id != nil %>
      <div class="create-btn-contents">
        <%= f.submit "編集する" ,class:"create-btn" %>
        <%=link_to 'もどる', trip_schedule_path(@trip.id, @schedule.id), class:"back-btn" %>
      </div>
    <% else %>
      <div class="create-btn-contents">
        <%= f.submit "作成する" ,class:"create-btn" %>
        <%=link_to 'もどる', trip_path(@trip.id), class:"back-btn" %>
      </div>
    <% end %>
        
  <% end %>
</div>

app/views/shared/_trip_form.html.erb
<div class="trip-main">
  <%# @tripの中身でcreateとupdateを自動で判定 %>
  <%= form_with model: @trip, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="form-title">
      しおり名
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :name, class:"trip-text", id:"trip-name", placeholder:"例：卒業旅行" %>

    <div class="form-title">
      目的地
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :destination, class:"trip-text", id:"trip-destination", placeholder:"例：沖縄" %>

    <div class="form-title">
      しおり概要
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :text, class:"trip-text", id:"trip-info", placeholder:"例：いつものメンバーで！" %>

    <div class="date-input">
      <div class="start-date-input">
        <div class="form-title">
          開始日
          <span class="indispensable">必須</span>
        </div>
        <div class='input-date-wrap'>
          <%= raw sprintf(
                  f.date_select(
                    :start_day,
                    class:'select-date',
                    id:"start-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: Time.now.year,
                    end_year: (Time.now.year + 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
        </div>
      </div>

      <div class="finish-date-input">
        <div class="form-title">
          終了日
          <span class="indispensable">必須</span>
        </div>
        <div class='input-date-wrap'>
          <%= raw sprintf(
                  f.date_select(
                    :finish_day,
                    class:'select-date',
                    id:"finish-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: Time.now.year,
                    end_year: (Time.now.year + 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
        </div>
      </div>
    </div>

    <div class="form-title">
      参加メンバー
      <span class="indispensable">必須</span><br>
      ※複数選択可(CtrlやShiftキーを押しながら選択してください)
    </div>

    <div class="trip-members">
      <%= f.collection_select(:user_ids, User.where.not(id: current_user.id), :id, :nickname, {}, {multiple: true, size: 5}) %>
      <input name="trip[user_ids][]" type="hidden" value=<%= current_user.id %>> 
    </div>

    <%# 作成・編集ボタン %>
    <% if @trip.id != nil %>
      <div class="create-btn-contents">
        <%= f.submit "編集する" ,class:"create-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
    <% else %>
      <div class="create-btn-contents">
        <%= f.submit "作成する" ,class:"create-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
    <% end %>
        
  <% end %>
</div>